# .air.toml
# Config file for air: https://github.com/cosmtrek/air

# Working directory
root = "."
tmp_dir = "tmp"

[build]
# Command to build your app
cmd = "go build -o ./tmp/main ./cmd/api"
# The binary to run
bin = "tmp/main"
# Watch these files for changes and trigger a rebuild
include_ext = ["go", "tpl", "tmpl", "html"]
# Ignore these folders
exclude_dir = ["tmp", "vendor", "logs", "logs_host"]
# Watch these directories
include_dir = ["cmd", "internal"]
# Log name
log = "air_errors.log"

[log]
# Show log time
time = true

[misc]
# Delete tmp folder on start
clean_on_exit = true
